[
  {
      "functor": "corl.glues.common.observe_sensor.ObserveSensor",
      "config": {
        "sensor": "Sensor_Position",
        "normalization": {
          "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
          "config": {
            "mu": 0.0,
            "sigma": [100, 100, 100],
          }
        }
      },
  },
  {
      "functor": "corl.glues.common.observe_sensor.ObserveSensor",
      "config": {
        "sensor": "Sensor_Velocity",
        "output_units": ["m/s", "m/s", "m/s"],
        "normalization": {
          "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
          "config": {
            "mu": 0.0,
            "sigma": [0.5, 0.5, 0.5],
        }
      },
    },
  },
  {
      "functor": "corl.glues.common.observe_sensor.ObserveSensor",
      "config": {
        "sensor": "Sensor_InspectedPoints",
        "normalization": {
          "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
          "config": {
            "mu": 0.0,
            "sigma": [100.0],
        },
      },
    },
  },
  {
      "functor": "corl.glues.common.observe_sensor.ObserveSensor",
      "config": {
        "sensor": "Sensor_UninspectedPoints",
        "normalization": {
            "enabled": False
      },
    },
  },
  {
      "functor": "safe_autonomy_sims.glues.delta_v_glue.DeltaVGlue",
      "config":
        {
          "sensor": "Sensor_Position",
          "training_export_behavior": "EXCLUDE",
        }
  },
]