[{
    "functor": "corl.glues.common.observe_sensor.ObserveSensor",
    "config": {
      "sensor": "Sensor_Quaternion",
      "normalization": {
          "enabled": False
    },
  },
},
{
    "functor": "corl.glues.common.observe_sensor.ObserveSensor",
    "config": {
      "sensor": "Sensor_AngularVelocity",
      "normalization": {
        "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
        "config": {
          "mu": 0.0,
          "sigma": [0.05, 0.05, 0.05],
        }
      }
    },
},]