#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Reinforcement Learning Core (CoRL) Safe Autonomy Extension.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------

"agent": "corl.agents.base_agent.TrainableBaseAgent"
"config": {
    "parts": [
        {"part": "Controller_Thrust", "config": {"name": "X Thrust", "axis": 0, properties: {name: "x_thrust"}}},
        {"part": "Controller_Thrust", "config": {"name": "Y Thrust", "axis": 1, properties: {name: "y_thrust"}}},
        {"part": "Controller_Thrust", "config": {"name": "Z Thrust", "axis": 2, properties: {name: "z_thrust"}}},
        {"part": "Sensor_Position"},
        {"part": "Sensor_Velocity"},
        {"part": "Sensor_InspectedPoints"}
    ],
    "episode_parameter_provider": {
        "type": "corl.episode_parameter_providers.simple.SimpleParameterProvider"
    },
    "simulator_reset_parameters": {
      "radius": {
        "type": "corl.libraries.parameters.UniformParameter",
        "config": {
          "name": "radius",
          "units": "meters",
          "low": 50,
          "high": 100,
        }
      },
      "azimuth_angle": {
        "type": "corl.libraries.parameters.UniformParameter",
        "config": {
          "name": "azimuth_angle",
          "units": "radians",
          "low": 0,
          "high": 6.283,
        }
      },
      "elevation_angle": {
        "type": "corl.libraries.parameters.UniformParameter",
        "config": {
          "name": "elevation_angle",
          "units": "radians",
          "low": -1.57,
          "high": 1.57,
        }
      },
      "vel_max_ratio": {
        "type": "corl.libraries.parameters.UniformParameter",
        "config": {
          "name": "vel_max_ratio",
          "low": 0,
          "high": 0.8,
        }
      },
      "vel_azimuth_angle": {
        "type": "corl.libraries.parameters.UniformParameter",
        "config": {
          "name": "vel_azimuth_angle",
          "units": "radians",
          "low": 0,
          "high": 6.283,
        }
      },
      "vel_elevation_angle": {
        "type": "corl.libraries.parameters.UniformParameter",
        "config": {
          "name": "vel_elevation_angle",
          "units": "radians",
          "low": -1.57,
          "high": 1.57,
        }
      },
    },
    "glues": [
        {
            "functor": "saferl.rta.cwh.inspection_rta_1v1.RTAGlueCWHInspection1v1",
            "config": {
              "state_observation_names": ["ObserveSensor_Sensor_Position", "ObserveSensor_Sensor_Velocity"],
              "enabled": False, #set to True to turn RTA on
              # No constraints listed defaults to all constraints active
              # Constraint options: "chief_collision", "rel_vel", "sun", "r_max", "PSM", "x_vel", "y_vel", "z_vel"
              # More details here: https://github.com/act3-ace/run-time-assurance/-/blob/main/run_time_assurance/zoo/cwh/inspection_1v1.py
              "constraints": ["chief_collision", "rel_vel"],
          },
          "references": {
            "step_size": "step_size",
            "collision_radius": "collision_radius",
            "v0": "velocity_threshold",
            "v0_distance": "collision_radius",
            "v1_coef": "vel_limit_slope",
            "n": "mean_motion",
            "r_max": "max_distance",
          },
          "wrapped": [
            {
                "functor": "corl.glues.common.controller_glue.ControllerGlue",
                "config": {
                    "controller": "X Thrust",
                    "training_export_behavior": "EXCLUDE",
                    "normalization": {
                      "enabled": False,
                    }
                },
            },
            {
                "functor": "corl.glues.common.controller_glue.ControllerGlue",
                "config":{
                    "controller": "Y Thrust",
                    "training_export_behavior": "EXCLUDE",
                    "normalization": {
                      "enabled": False,
                    }
                }
            },
            {
                "functor": "corl.glues.common.controller_glue.ControllerGlue",
                "config":{
                  "controller": "Z Thrust",
                  "training_export_behavior": "EXCLUDE",
                  "normalization": {
                    "enabled": False,
                  }
                }
            },
          ],
        },
        {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config": {
              "sensor": "Sensor_Position",
              "normalization": {
                "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
                "config": {
                  "mu": 0.0,
                  "sigma": [100, 100, 100],
                }
              }
            },
        },
        {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config": {
              "sensor": "Sensor_Velocity",
              "output_units": ["m/s", "m/s", "m/s"],
              "normalization": {
                "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
                "config": {
                  "mu": 0.0,
                  "sigma": [0.5, 0.5, 0.5],
              }
            },
          },
        },
        {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config": {
              "sensor": "Sensor_InspectedPoints",
              "normalization": {
                  "enabled": False
            },
          },
        },
        {
          "functor": "corl.glues.common.magnitude.MagnitudeGlue",
            "config": {
              "normalization": {
                "normalizer": "corl.libraries.normalization.StandardNormalNormalizer"
              },
            },
            "wrapped": {
                "functor": "corl.glues.common.observe_sensor.ObserveSensor",
                "config":{
                    "sensor": Sensor_Velocity,
                },
            },
        },
        {
            "functor": "saferl.glues.vel_limit_glue.VelocityLimitGlue",
            "config":
              {
                "sensor": "Sensor_Position",
              },
            "references": {
              "velocity_threshold": "velocity_threshold",
              "threshold_distance": "collision_radius",
              "mean_motion": "mean_motion",
              "slope": "vel_limit_slope",
            },
        },
    ],
    "dones": [
        {
            # Max distance from origin
            "functor": "saferl.dones.cwh.common.MaxDistanceOriginDoneFunction",
            "references": {
              "max_distance": "max_distance",
            },
        },
        {
            # Crash into origin (exceeded velocity constraint within crashing region)
            "functor": "saferl.dones.cwh.common.CrashOriginDoneFunction",
            "references": {
              "crash_region_radius": "collision_radius",
            },
        },
        {
            # Success (inspected all points)
            "functor": "saferl.dones.cwh.inspection_dones.SuccessfulInspectionDoneFunction",
            "config":{},
        },
    ],
    "rewards": [
        {
            # reward = number of newly observed points
            "name": "ObservedPointsReward",
            "functor": "saferl.rewards.cwh.inspection_rewards.ObservedPointsReward",
            "config": {
              "scale": 0.01
            }
        },
        {
            # reward = scale (if all points are inspected)
            "name": "InspectionSuccessReward",
            "functor": "saferl.rewards.cwh.inspection_rewards.InspectionSuccessReward",
            "config": {
              "scale": 1.0,
            }
        },
        {
          # reward = scale (if crash occurs)
          "name": "InspectionCrashOriginReward",
          "functor": "saferl.rewards.cwh.inspection_rewards.InspectionCrashOriginReward",
          "config": {
            "scale": -1.0,
          },
          "references": {
            "crash_region_radius": "collision_radius",
          },
        },
        {
          "name": "InspectionVelocityConstraintReward",
          "functor": "saferl.rewards.cwh.docking_rewards.DockingVelocityConstraintReward",
          "config": {
            "scale": -0.01,
            "bias": -0.01,
            "lower_bound": False,
          },
          "references": {
            "velocity_threshold": "velocity_threshold",
            "threshold_distance": "collision_radius",
            "mean_motion": "mean_motion",
          },
        },
        {
          # reward = scale (if RTA is intervening)
          "name": "InspectionRTAReward",
          "functor": "saferl.rewards.rta_rewards.RTAInterveningReward",
          "config": {
            "scale": -0.01,
          }
        },
    ],
    "reference_store": !include ../parameters/inspection_3d.yml
}
