#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Reinforcement Learning Core (CoRL) Safe Autonomy Extension.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------

"agent": "corl.agents.base_agent.TrainableBaseAgent"
"config": {
    "parts": [
        {"part": "Controller_Thrust", "config": {"name": "X Thrust", "axis": 0, properties: {name: "x_thrust"}}},
        {"part": "Controller_Thrust", "config": {"name": "Y Thrust", "axis": 1, properties: {name: "y_thrust"}}},
        {"part": "Controller_Thrust", "config": {"name": "Z Thrust", "axis": 2, properties: {name: "z_thrust"}}},
        {"part": "Sensor_Position"},
        {"part": "Sensor_Velocity"}
    ],
    "episode_parameter_provider": {
        "type": "corl.episode_parameter_providers.simple.SimpleParameterProvider"
    },
    "simulator_reset_parameters": {
      "x": {
        "type": "corl.libraries.parameters.UniformParameter",
        "config": {
          "name": "x",
          "units": "meters",
          "low": -100,
          "high": 100,
        }
      },
      "y": {
        "type": "corl.libraries.parameters.UniformParameter",
        "config": {
          "name": "x",
          "units": "meters",
          "low": -100,
          "high": 100,
        }
      },
      "z": {
        "type": "corl.libraries.parameters.UniformParameter",
        "config": {
          "name": "x",
          "units": "meters",
          "low": -100,
          "high": 100,
        }
      },
      "xdot": 0,
      "ydot": 0,
      "zdot": 0,
    },
    "glues": [
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config": {
                "controller": "X Thrust",
                "training_export_behavior": "EXCLUDE",
                "normalization": {
                  "enabled": False,
                }
            },
        },
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config":{
                "controller": "Y Thrust",
                "training_export_behavior": "EXCLUDE",
                "normalization": {
                  "enabled": False,
                }
            }
        },
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config":{
              "controller": "Z Thrust",
              "training_export_behavior": "EXCLUDE",
              "normalization": {
                "enabled": False,
              }
            }
        },
        {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config": {
              "sensor": "Sensor_Position",
              "normalization": {
                "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
                "config": {
                  "mu": 0.0,
                  "sigma": [100, 100, 100],
                }
              }
            },
        },
        {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config": {
              "sensor": "Sensor_Velocity",
              "normalization": {
                "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
                "config": {
                  "mu": 0.0,
                  "sigma": [0.5, 0.5, 0.5],
              }
            },
          },
        },
        {
          "functor": "corl.glues.common.magnitude.MagnitudeGlue",
            "config": {
              "normalization": {
                "normalizer": "corl.libraries.normalization.StandardNormalNormalizer"
              },
            },
            "wrapped": {
                "functor": "corl.glues.common.observe_sensor.ObserveSensor",
                "config":{
                    "sensor": Sensor_Velocity,
                },
            },
        },
        {
            "functor": "saferl.glues.vel_limit_glue.VelocityLimitGlue",
            "config":
              {
                "sensor": "Sensor_Position",
                "velocity_threshold": 0.2,
                "threshold_distance": 0,
                "mean_motion": 0.001027,
                "slope": 2.0,
              }
        },
    ],
    "dones": [
        {
            # Max distance from origin
            "functor": "saferl.dones.cwh.common.MaxDistanceOriginDoneFunction",
            "config":{
                "max_distance": 500,
            },
        },
        {
            # Crash into origin (exceeded velocity constraint within crashing region)
            "functor": "saferl.dones.cwh.common.CrashOriginDoneFunction",
            "config":{
              "crash_region_radius": 10,
              "velocity_constraint": {
                "velocity_threshold": 0.2,
                "threshold_distance": 0,
              },
            },
        },
        {
            # Success (inspected all points)
            "functor": "saferl.dones.cwh.inspection_dones.SuccessfulInspectionDoneFunction",
            "config":{},
        },
    ],
    "rewards": [
        {
            # reward = number of newly observed points
            "name": "ObservedPointsReward",
            "functor": "saferl.rewards.cwh.inspection_rewards.ObservedPointsReward",
            "config": {}
        },
        {
            # reward = scale + time_component
            # time_component = 1 - (sim_time/timeout) or 0 if no timeout given
            "name": "InspectionSuccessReward",
            "functor": "saferl.rewards.cwh.inspection_rewards.InspectionSuccessReward",
            "config": {
              "scale": 1.0,
              "timeout": 10000,
            }
        },
        {
          # reward = timeout_reward if timeout reached else 0
          "name": "InspectionFailureReward",
          "functor": "saferl.rewards.cwh.inspection_rewards.InspectionFailureReward",
          "config": {
            "timeout_reward": -1.0,
            "timeout": 10000,
          }
        },
    ],
}
