#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Reinforcement Learning (RL) Core Extension.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------

"config": "configs/cwh3d/six-dof-inspection-multiagent-v2/task.yml"
"platform_config":
  - name: "blue0"
    config: "configs/cwh3d/six_dof_platform.yml"
  - name: "blue1"
    config: "configs/cwh3d/six_dof_platform.yml"
  - name: "blue2"
    config: "configs/cwh3d/six_dof_platform.yml"
"agent_config":
  - name: "blue0_ctrl"
    platforms: ["blue0"]
    config: "configs/cwh3d/six-dof-inspection-multiagent-v2/agent.yml"
    policy: "configs/common/policies/ppo.yml"
  - name: "blue1_ctrl"
    platforms: ["blue1"]
    config: "configs/cwh3d/six-dof-inspection-multiagent-v2/agent.yml"
    policy: "configs/common/policies/ppo.yml"
  - name: "blue2_ctrl"
    platforms: ["blue2"]
    config: "configs/cwh3d/six-dof-inspection-multiagent-v2/agent.yml"
    policy: "configs/common/policies/ppo.yml"
