include:
  - project: devsecops/cicd/pipeline
    ref: v15.0.6
    file: main.yml

variables:
  PIP_INDEX_URL: https://pypi.org/simple/
  SRC_DIR: safe_autonomy_sims
  ACT3_SECRETS_AUTH_TOML: $POETRY_AUTH_TOML

build image:
  variables:
    TARGET_STAGE: cicd

build tagged image:
  variables:
    TARGET_STAGE: build
    DESTINATION_PATH: /releases

build development image:
  extends: build tagged image
  variables:
    TARGET_STAGE: develop
    DESTINATION_PATH: /development/$TARGET_STAGE

build package image:
  extends: build tagged image
  variables:
    TARGET_STAGE: package
    DESTINATION_PATH: /releases/$TARGET_STAGE

# Overriding mkdocs because the ci-mkdocs image uses Python 3.9.18.  Poetry can't find
# grpcio for Python 3.9 due to sha256 checksum not matching the expected value.
mkdocs:
  needs: [ "build image" ]
  image:
    name: $CI_REGISTRY_IMAGE/cicd:ci-$CI_PIPELINE_ID
    entrypoint: ['']
  variables:
    MKDOCS_PDF_EXPORT: 1
  script:
    - mkdocs build
  artifacts:
    paths:
      - site/

python unit test:
  script:
    - pytest -m unit_test ${UNIT_TEST_DIR} --cov=${SRC_DIR} --cov-report term-missing --cov-report xml --cov-report html --junitxml=pytest-junit.xml   
    - sed -i 's;/'"${SRC_DIR}"'</source>;</source>;' coverage.xml
    - sed -i 's;filename=";filename="'"${SRC_DIR}"'/;' coverage.xml

