# -------------------------------------------------------------------------------
#
# Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
# Reinforcement Learning (RL) Core Extension
#
# This is a US Government Work not subject to copyright protection in the US.
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# -------------------------------------------------------------------------------
version: "3.7"
# some environment variables in this compose (for example $CODE_PATH) are set by the .env file in the repo root directory
# to change those variables change them in the .env file not in this compose file

services:
  dummy:
    build:
      context: .
      dockerfile: Dockerfile
      args: &default-args
        NEW_USER: $NEW_USER
        NEW_GROUP: $NEW_GROUP
        NEW_UID: $NEW_UID
        NEW_GID: $NEW_GID
        APT_MIRROR_URL: $APT_MIRROR_URL
        SECURITY_MIRROR_URL: $SECURITY_MIRROR_URL
        NVIDIA_MIRROR_URL: $NVIDIA_MIRROR_URL
        ACT3_OCI_REGISTRY: $ACT3_OCI_REGISTRY
        AGENTS_BASE_IMAGE: $AGENTS_BASE_IMAGE
        OCI_REGISTRY: $OCI_REGISTRY

    environment: &default-environment
      SSH_AUTH_SOCK: "$SSH_AUTH_SOCK"
      DISPLAY: "$DISPLAY"

    volumes: &development-volumes
      # passing through this file allows opening windows from the container in your host computer
      # *** NOTE THIS IS LINUX SPECIFIC ITEM *** Updates needed for Virtual based setups
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      #
      # for development, link the host folder containing code to /opt/project in container
      - "$CODE_PATH/:/opt/project"
      - "$CODE_PATH/../corl/corl/:/opt/conda/lib/python3.8/site-packages/corl"
      #
      # for development, link the host folder containing data to /opt/data/safe_autonomy_sims in container
      - "$DATA_PATH:/opt/data/safe_autonomy_sims"
      #
      # copy in command history
      - "safe-autonomy-sims-bashhistory:/commandhistory"
      #
      # VSCODE items
      - "vscode-server-extensions:/home/$NEW_USER/.vscode-server/extensions"
      - "vscode-server-extensions-insiders:/home/$NEW_USER/.vscode-server-insiders/extensions"
      #
      # .ssh
      # - "$HOME/.ssh/:/home/$NEW_USER/.ssh/"
      # - "$HOME/.duoconnect/:/home/$NEW_USER/.duoconnect/"

  develop:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
      args:
        <<: *default-args

    image: $OCI_REGISTRY/rta/safe-autonomy-stack/safe-autonomy-sims/develop:latest
  #   # ray wants shm_size but the size depends on available RAM on each machine
  #   # shm_size: $SHM_SIZE

  build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
      args:
        <<: *default-args

  # Defines the build environment for the safe-autonomy-sims items within a vscode setup
  safe-autonomy-sims:
    build:
      context: .
      dockerfile: Dockerfile
      target: user-base-builder
      args:
        <<: *default-args


    # set user to your user id which is usually 1000:1000 (ubuntu) or 1001:1001 (RHEL)
    # to check you user id run `echo $(id -u):$(id -g)`
    user: $UID:$GID
    # shm_size: $SHM_SIZE

    environment:
      <<: *default-environment

    # for development, link the host folder containing code to /opt/project in container
    volumes: *development-volumes

    # Overrides default command so things don't shut down after the process ends.
    command: dumb-init fixuid sleep infinity

volumes:
  safe-autonomy-sims-bashhistory:
  vscode-server-extensions:
  vscode-server-extensions-insiders:

networks:
  default:
    name: rta
