#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Reinforcement Learning (RL) Core  Extension.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------
site_name: Safe-Autonomy-Sims
site_author: Safe-Autonomy Team
repo_url: https://github.com/act3-ace/safe-autonomy-sims
docs_dir: "docs"
site_url: https://github.com/act3-ace/
edit_uri: blob/main/docs/
site_dir: site
site_description: "The following python project creates a python interface for training Deep RL - provides the base RL functionality and APIs to enable rapid ablation testing and setup"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
  - autorefs
  - gen-files:
      scripts:
        - docs/gen_ref_nav.py  # or any other name or path
  - section-index
  - pdf-export:
      verbose: false
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
      combined: true


theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
  - navigation.tabs
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode


extra_css:
  - css/style.css
  - css/material.css
  - css/mkdocstrings.css


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.arithmatex:  # MathJax (latex)
      generic: true

extra_javascript:
  # Mermaid
  - https://unpkg.com/mermaid@8.4.2/dist/mermaid.min.js
  # MathJax (latex)
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

handlers:
  python:
    setup_commands:
    - import sys
    - sys.path.append("docs")
    selection:
      new_path_syntax: yes
    import:  # demonstration purpose in the docs
      - https://docs.python-requests.org/en/master/objects.inv

nav:
  - "Introduction": index.md
  - "Install": install.md
  - "Concepts": concepts.md
  - "Configuration": configuration.md
  - "Tasks":
      - tasks/index.md
      - "2D Dubins Rejoin": tasks/2d_rejoin_task.md
      - "3D Dubins Rejoin": tasks/3d_rejoin_task.md
      - "3D CWH Docking": tasks/3d_docking_task.md
#  - "Changelog": change_log.md
#  - "License": license.md
  - "API":
#      - reference/SUMMARY.md  # API "Table of Contents"
      - api/index.md
      - "agents":
          - api/agents/index.md
          - "rta agent":
              - reference/agents/rta_agent.md
      - "dones":
          - api/dones/index.md
          - "common dones":
              - reference/dones/common_dones.md
          - "docking dones":
              - reference/dones/docking_dones.md
          - "rejoin dones":
              - reference/dones/rejoin_dones.md
      - "glues":
          - api/glues/index.md
          - "normal":
              - api/glues/normal/index.md
              - reference/glues/normal/normal_glue.md
              - reference/glues/normal/normal_observe_glue.md
              - reference/glues/normal/normal_wrapper_glue.md
          - reference/glues/magnitude_glue.md
          - reference/glues/rejoin_region_glue.md
          - reference/glues/rta_glue.md
          - reference/glues/unit_vector_glue.md
          - reference/glues/vel_limit_glue.md
      - "platforms":
          - api/platforms/index.md
          - "common":
              - reference/platforms/common/sensors.md
          - "cwh":
              - api/platforms/cwh/index.md
              - reference/platforms/cwh/cwh_available_platforms.md
              - reference/platforms/cwh/cwh_controllers.md
              - reference/platforms/cwh/cwh_platform.md
              - reference/platforms/cwh/cwh_properties.md
              - reference/platforms/cwh/cwh_sensors.md
          - "dubins":
              - api/platforms/dubins/index.md
              - "sensors":
                  - api/platforms/dubins/sensors/index.md
                  - "dubins sensors":
                      - reference/platforms/dubins/sensors/dubins_sensors.md
                  - "partner sensors":
                      - reference/platforms/dubins/sensors/partner_sensors.md
                  - "relative sensors":
                      - reference/platforms/dubins/sensors/relative_sensors.md
              - reference/platforms/dubins/dubins_available_platforms.md
              - reference/platforms/dubins/dubins_controllers.md
              - reference/platforms/dubins/dubins_platform.md
              - reference/platforms/dubins/dubins_properties.md
      - "rewards":
          - api/rewards/index.md
          - "docking rewards":
              - reference/rewards/docking_rewards.md
          - "rejoin rewards":
              - reference/rewards/rejoin_rewards.md
      - "rta":
          - api/rta/index.md
          - "cwh_rta":
              - reference/rta/cwh/cwh_rta.md
      - "simulators":
          - api/simulators/index.md
          - "cwh simulator":
              - reference/simulators/cwh_simulator.md
          - "dubins simulator":
              - reference/simulators/dubins_simulator.md
          - "saferl simulator":
              - reference/simulators/saferl_simulator.md
      - "utils": reference/utils.md
