site_name: Safe-Autonomy-Sims
site_author: Safe-Autonomy Team
repo_url: https://github.com/act3-ace/safe-autonomy-sims
docs_dir: "docs"

plugins:
  - search
  - macros
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
  - inari:
      module: saferl
      out-name: saferl

markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://unpkg.com/mermaid@8.4.2/dist/mermaid.min.js

nav:
  - "Introduction": index.md
  - "About": about.md
  - "API":
    - saferl/index.md
    - Dones:
      - saferl/dones/index.md
      - saferl/dones/docking_dones-py.md
    - Glues:
      - saferl/glues/index.md
      - saferl/glues/combined_controller_glue-py.md
      - saferl/glues/rta_glue-py.md
    - Platforms:
      - saferl/platforms/index.md
      - CWH:
        - saferl/platforms/cwh/index.md
      - Dubins:
        - saferl/platforms/dubins/index.md
    - Rewards:
      - saferl/rewards/index.md
      - saferl/rewards/docking_rewards-py.md
    - Simulators:
      - saferl/simulators/index.md
theme: material
