site_name: Safe-Autonomy-Sims
site_author: Safe-Autonomy Team
repo_url: https://github.com/act3-ace/safe-autonomy-sims
docs_dir: "docs"

plugins:
  - search
  - macros
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
  - inari:
      module: saferl
      out-name: saferl

markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://unpkg.com/mermaid@8.4.2/dist/mermaid.min.js

nav:
  - "Introduction": index.md
  - "About": about.md
  - "API":
    - saferl/index.md
    - Dones:
      - dones/index.md
      - dones/docking_dones-py.md
    - Glues:
      - glues/index.md
      - glues/combined_controller_glue-py.md
      - glues/rta_glue-py.md
    - Platforms:
      - platforms/index.md
      - CWH:
        - cwh/index.md
      - Dubins:
        - dubins/index.md
    - Rewards:
      - rewards/index.md
      - rewards/docking_rewards-py.md
    - Simulators:
      - simulators/index.md
theme: material
