site_name: Safe-Autonomy-Sims
site_author: Safe-Autonomy Team
repo_url: https://github.com/act3-ace/safe-autonomy-sims
docs_dir: "docs"

plugins:
  - search
  - macros
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
  - inari:
      module: saferl
      out-name: saferl

markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://unpkg.com/mermaid@8.4.2/dist/mermaid.min.js

nav:
  - "Introduction": index.md
  - "About": about.md
  - "API":
    - saferl/index.md
    - backend:
        - saferl/backend/index.md
        - base_models:
          - saferl/backend/base_models/index.md
          - saferl/backend/base_models/entities-py.md
        - cwh:
          - saferl/backend/cwh/index.md
          - saferl/backend/cwh/cwh-py.md
        - dubins:
          - saferl/backend/dubins/index.md
          - saferl/backend/dubins/entities-py.md
    - core:
        - saferl/core/index.md
        - saferl/core/utils-py.md
        - agents:
          - saferl/core/agents/index.md
          - saferl/core/agents/rta_agent-py.md
        - dones:
          - saferl/core/dones/index.md
          - saferl/core/dones/common_dones-py.md
          - saferl/core/dones/docking_dones-py.md
          - saferl/core/dones/rejoin_dones-py.md
        - glues:
          - saferl/core/glues/index.md
          - saferl/core/glues/magnitude_glue-py.md
          - saferl/core/glues/rejoin_region_glue-py.md
          - saferl/core/glues/rta_glue-py.md
          - saferl/core/glues/unit_vector_glue-py.md
          - saferl/core/glues/vel_limit_glue-py.md
          - normal:
            - saferl/core/glues/normal/index.md
            - saferl/core/glues/normal/normal_glue-py.md
            - saferl/core/glues/normal/normal_observe_glue-py.md
            - saferl/core/glues/normal/normal_wrapper_glue-py.md
        - platforms:
          - saferl/core/platforms/index.md
          - common:
            - saferl/core/platforms/common/index.md
            - saferl/core/platforms/common/sensors-py.md
          - cwh:
            - saferl/core/platforms/cwh/index.md
            - saferl/core/platforms/cwh/cwh_available_platforms-py.md
            - saferl/core/platforms/cwh/cwh_controllers-py.md
            - saferl/core/platforms/cwh/cwh_platform-py.md
            - saferl/core/platforms/cwh/cwh_properties-py.md
            - saferl/core/platforms/cwh/cwh_sensors-py.md
          - dubins:
            - saferl/core/platforms/dubins/index.md
            - saferl/core/platforms/dubins/dubins_available_platforms-py.md
            - saferl/core/platforms/dubins/dubins_controllers-py.md
            - saferl/core/platforms/dubins/dubins_platform-py.md
            - saferl/core/platforms/dubins/dubins_properties-py.md
            - sensors:
              - saferl/core/platforms/dubins/sensors/index.md
              - saferl/core/platforms/dubins/sensors/dubins_sensors-py.md
              - saferl/core/platforms/dubins/sensors/partner_sensors-py.md
              - saferl/core/platforms/dubins/sensors/relative_sensors-py.md
        - rewards:
          - saferl/core/rewards/index.md
          - saferl/core/rewards/docking_rewards-py.md
          - saferl/core/rewards/rejoin_rewards-py.md
        - rta:
          - saferl/core/rta/index.md
          - saferl/core/rta/base_rta-py.md
          - cwh:
            - saferl/core/rta/cwh/index.md
            - saferl/core/rta/cwh/cwh_rta-py.md
        - simulators:
          - saferl/core/simulators/index.md
          - saferl/core/simulators/cwh_simulator-py.md
          - saferl/core/simulators/dubins_simulator-py.md
          - saferl/core/simulators/saferl_simulator-py.md
theme: material
