{
    "policy_class": corl.policies.scripted_action.ScriptedActionPolicy,
    "train": False,

    "config": {
        "controllers": [
            ['Controller_Acceleration_Acceleration', 'acceleration'],
            ['Controller_YawRate_Yaw_rate', 'yaw_rate'],
        ],

        "time_extractor": {
            "fields": ["ObserveSensor_Sensor_Time", "direct_observation"],
            'indices': [0]
        },

        "control_times": [],
        "control_values" : [],
        "default_action": [0, 0],
        "missing_action_policy": "default_action"
    }
}
