#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Reinforcement Learning (RL) Core  Extension.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------
{
    "policy_class": corl.policies.scripted_action.ScriptedActionPolicy,
    "train": False,

    "config": {
        "controllers": [
            ['Controller_Acceleration_Acceleration', 'acceleration'],
            ['Controller_PitchRate_Pitch_rate', 'pitch_rate'],
            ['Controller_RollRate_Roll_rate', 'roll_rate'],
        ],

        "time_extractor": {
            "fields": ["ObserveSensor_Sensor_Time", "direct_observation"],
            'indices': [0]
        },

        "control_times": [],
        "control_values" : [],
        "default_action": [0, 0, 0],
        "missing_action_policy": "default_action"
    }
}
