#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Reinforcement Learning (RL) Core  Extension.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------

"agent": "corl.agents.base_agent.TrainableBaseAgent"
"config": {
    "parts": [
        {"part": "Controller_RollRate", "config": {"axis": 0}},
        {"part": "Controller_PitchRate", "config": {"axis": 1}},
        {"part": "Controller_Acceleration", "config": {"axis": 2}},
        {"part": "Sensor_Relative_Position", "config": {"oriented": True}},
        {"part": "Sensor_Relative_Rejoin_Position", "config": {"oriented": True, "offset": [500, 500, 0]}},
        {"part": "Sensor_Velocity", "config": {"oriented": True}},
        {"part": "Sensor_Partner_Velocity", "config": {"oriented": True}},
        {"part": "Sensor_Flight_Path_Angle"},
        {"part": "Sensor_Roll"},
    ],
    "episode_parameter_provider": {
      "type": "corl.episode_parameter_providers.simple.SimpleParameterProvider"
    },
    "simulator_reset_parameters": {
      "x": 0,
      "y": 0,
      "z": 10000,
      "heading": 0,
      "v": 200,
      "gamma": 0,
      "roll": 0
    },
    "glues": [
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config": {
                "controller": "Controller_Acceleration",
                "training_export_behavior": "EXCLUDE",
                "normalization": {
                  "enabled": False,
                }
            },
        },
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config":{
                "controller": "Controller_PitchRate",
                "training_export_behavior": "EXCLUDE",
                "normalization": {
                  "enabled": False,
                }
            }
        },
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config":{
                "controller": "Controller_RollRate",
                "training_export_behavior": "EXCLUDE",
                "normalization": {
                  "enabled": False,
                }
            }
        },
        {
          "functor": "corl.glues.common.magnitude.MagnitudeGlue",
          "config": {
            "normalization": {
              "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
              "config": {
                "mu": 0.0,
                "sigma": 1000.0,
              },
            },
          },
          "wrapped": {
              "functor": "corl.glues.common.observe_sensor.ObserveSensor",
              "config":{
                  "sensor": Sensor_Relative_Position,
              },
          },
        },
        {
          "functor": "corl.glues.common.unit_vector_glue.UnitVectorGlue",
          "config": {
            "normalization": {
              "config": {
                "mu": 0.0,
                "sigma": [1, 1, 1],
              }
            },
          },
          "wrapped": {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config":{
                "sensor": Sensor_Relative_Position,
            },
          },
        },
        {
          "functor": "corl.glues.common.magnitude.MagnitudeGlue",
          "config": {
            "normalization": {
              "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
              "config": {
                "mu": 0.0,
                "sigma": 1000.0,
              },
            },
          },
          "wrapped": {
              "functor": "corl.glues.common.observe_sensor.ObserveSensor",
              "config":{
                  "sensor": Sensor_Relative_Rejoin_Position,
              },
          },
        },
        {
          "functor": "corl.glues.common.unit_vector_glue.UnitVectorGlue",
          "config": {
            "normalization": {
              "config": {
                "mu": 0.0,
                "sigma": [1, 1, 1],
              }
            }
          },
          "wrapped": {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config":{
              "sensor": Sensor_Relative_Rejoin_Position,
            },
          },
        },
        {
          "functor": "corl.glues.common.magnitude.MagnitudeGlue",
          "config": {
            "normalization": {
              "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
              "config": {
                "mu": 0.0,
                "sigma": 400.0,
              },
            },
          },
          "wrapped": {
              "functor": "corl.glues.common.observe_sensor.ObserveSensor",
              "config":{
                  "sensor": Sensor_Velocity,
              },
          },
        },
        {
          "functor": "corl.glues.common.unit_vector_glue.UnitVectorGlue",
          "config": {
            "normalization": {
              "config": {
                "mu": 0.0,
                "sigma": [1, 1, 1],
              }
            }
          },
          "wrapped": {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config":{
              "sensor": Sensor_Velocity,
            },
          },
        },
        {
          "functor": "corl.glues.common.magnitude.MagnitudeGlue",
          "config": {
            "normalization": {
              "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
              "config": {
                "mu": 0.0,
                "sigma": 400.0,
              },
            },
          },
          "wrapped": {
              "functor": "corl.glues.common.observe_sensor.ObserveSensor",
              "config":{
                  "sensor": Sensor_Partner_Velocity,
              },
          },
        },
        {
          "functor": "corl.glues.common.unit_vector_glue.UnitVectorGlue",
          "config": {
            "normalization": {
              "config": {
                "mu": 0.0,
                "sigma": [1, 1, 1],
              }
            }
          },
          "wrapped": {
              "functor": "corl.glues.common.observe_sensor.ObserveSensor",
              "config":{
                  "sensor": Sensor_Partner_Velocity,
              },
          },
        },
        {
          "functor": "corl.glues.common.observe_sensor.ObserveSensor",
          "config": {
            "sensor": "Sensor_Roll",
            "normalization": {
              "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
              "config": {
                "mu": 0.0,
                "sigma": 1.04719755,  # pi/3
              }
            }
          },
        },
        {
          "functor": "corl.glues.common.observe_sensor.ObserveSensor",
          "config": {
            "sensor": "Sensor_Flight_Path_Angle",
            "normalization": {
              "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
              "config": {
                "mu": 0.0,
                "sigma": 0.34906585039,  # pi/9
              }
            }
          },
        },
    ],
    "dones": [
        {
            "functor": "saferl.dones.rejoin_dones.MaxDistanceDoneFunction",
            "config":{},
            "references": {
              "max_distance": "max_distance",
              "lead": "lead",
            }
        },
        {
            "functor": "saferl.dones.rejoin_dones.CrashDoneFunction",
            "config":{},
            "references": {
              "lead": "lead",
              "safety_margin": "safety_margin",
            }
        },
        {
            "functor": "saferl.dones.rejoin_dones.RejoinSuccessDone",
            "config":{},
            "references": {
              "lead": "lead",
              "offset": "offset_0",
              "radius": "radius",
              "success_time": "success_time",
              "step_size": "step_size",
            }
        },
    ],
    "rewards": [
        {
            "name": "RejoinDistanceExponentialChangeReward",
            "functor": "saferl.rewards.rejoin_rewards.RejoinDistanceExponentialChangeReward",
            "config": {
                "pivot": 5000.0,
            },
            "references": {
              "lead": "lead",
              "offset": "offset_0",
            }
        },
        {
            "name": "RejoinReward",
            "functor": "saferl.rewards.rejoin_rewards.RejoinReward",
            "config": {
                "reward": 0.1,
                "refund": True,
            },
            "references": {
              "lead": "lead",
              "offset": "offset_0",
              "radius": "radius",
            }
        },
        {
            "name": "RejoinFirstTimeReward",
            "functor": "saferl.rewards.rejoin_rewards.RejoinFirstTimeReward",
            "config": {
                "reward": 0.25,
            },
            "references": {
              "lead": "lead",
              "offset": "offset_0",
              "radius": "radius",
            }
        },
        {
            "name": "RejoinSuccessReward",
            "functor": "saferl.rewards.rejoin_rewards.RejoinSuccessReward",
            "config": {
                "reward": 1,
              },
            "references": {
              "lead": "lead",
              "offset": "offset_0",
              "radius": "radius",
              "success_time": "success_time",
              "step_size": "step_size",
            }
        },
        {
            "name": "RejoinFailureReward",
            "functor": "saferl.rewards.rejoin_rewards.RejoinFailureReward",
            "config": {
                "crash_reward": -1,
                "distance_reward": -1,
                "timeout_reward": -1,
                "leave_rejoin_reward": 0,
                "max_time": 2000,
            },
            "references": {
              "safety_margin": "safety_margin",
              "max_distance": "max_distance",
              "lead": "lead",
              "offset": "offset_0",
              "radius": "radius",
            }
        },
    ],
    "reference_store": !include ../parameters/parameters.yml
}