#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Reinforcement Learning (RL) Core Extension.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------

####################################################################
# Override values used by the setup
####################################################################
experiment_class: corl.experiments.rllib_experiment.RllibExperiment
config:
  rllib_config_updates: &rllib_config_updates
    num_workers: 6

  # No overrides for ray as there are no changes
  ray_config_updates: &ray_config_updates
    local_mode: False
    _redis_password: null
    ignore_reinit_error: False

  # Change the default path for saving out the data
  env_config_updates: &env_config_updates
    TrialName: Dubins-Rejoin-3D
    output_path: ./output/env/

  # Change the default path for saving out the data
  tune_config_updates: &tune_config_updates

  ####################################################################
  # Setup the actual keys used by the code
  # Note that items are patched from the update section
  ###################################################################
  rllib_configs:
    default: [!include ../../../common/ray/rllib.yml, *rllib_config_updates]
    local: [!include ../../../common/ray/rllib.yml,  *rllib_config_updates]

  ray_config: [!include ../../../common/ray/ray.yml, *ray_config_updates]
  env_config: [!include ../environments/environment.yml, *env_config_updates]
  tune_config: [!include ../../../common/ray/tune.yml, *tune_config_updates]

