---
#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Reinforcement Learning Core (CoRL) Safe Autonomy Extension.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------

###################################
# Environment configuration options
###################################

{
  "simulator": {
      "type": "CWHSimulator", # Registered CoRL simulator
      "config": {},
  },
  "simulator_reset_parameters": {
      # Environment reset parameters
      # These will override any default reset parameters defined in other configuration files
      "initializer": {
          # Agent initializer which sets agent initial state given a set of initial conditions in polar coordinates
          "functor": "safe_autonomy_sims.simulators.initializers.docking_initializer.Docking3DRadialInitializer",
          "config":
            {
              "threshold_distance": 0.5,
              "velocity_threshold": 0.2,
              "mean_motion": 0.001027,
              "slope": 2.0,
            },
        },
      "additional_entities": {
          # Additional simulation entities in the environment not controlled by an agent
          "chief":
            {
              "platform": "cwh",
              "initializer": {
                "functor": "safe_autonomy_sims.simulators.initializers.cwh.PositionVelocityInitializer",
              },
              "config": {
                "x": 0, "y": 0, "z": 0, "x_dot": 0, "y_dot": 0, "z_dot": 0
              },
            },
        },
    },
  "platforms": "CWHSimulator_Platforms", # list of registered platform types allowed in the environment
  "plugin_paths": [
      "safe_autonomy_sims.platforms",
      "safe_autonomy_sims.simulators",
    ], # python namespaces to search for registered CoRL plugins (platforms and simulators)
  "episode_parameter_provider":
    {
      "type": "corl.episode_parameter_providers.simple.SimpleParameterProvider",
    },
}
