# ---------------------------------------------------------------------------
# //
#
# Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
# Reinforcement Learning (RL) Core contributed by the:
#  -  () Team
#  - Safe Autonomy (SA) Team
#
# This is a US Government Work not subject to copyright protection in the US.
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ---------------------------------------------------------------------------

{
  "simulator": "CWHSimulator",
  "platforms": "CWHSimulator_Platforms",
  "plugin_paths": ["saferl.platforms", "saferl.simulators"],
  "horizon": 2000,
  "sim_config": {
      "step_size": 1
  },
  "episode_parameter_provider": {
    "type": "act3_rl_core.episode_parameter_providers.simple.SimpleParameterProvider"
  },
}