# ---------------------------------------------------------------------------
# //
#
# Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
# Reinforcement Learning (RL) Core contributed by the:
#  -  () Team
#  - Safe Autonomy (SA) Team
#
# This is a US Government Work not subject to copyright protection in the US.
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ---------------------------------------------------------------------------

{
  "simulator": {
    "type": "Dubins3dSimulator",
    "config": {
      "lead": "red0",
      "step_size": 1
    },
  },
  "platforms": "DubinsSimulator_Platforms",
  "plugin_paths": ["saferl.core.platforms", "saferl.core.simulators"],
  "episode_parameter_provider": {
    "type": "act3_rl_core.episode_parameter_providers.simple.SimpleParameterProvider"
  },
  "dones": {
    "shared": [
      {
        "functor": "saferl.core.dones.common_dones.CollisionDoneFunction",
        "config": { safety_constraint: 100 },
      },
      {
        "functor": "saferl.core.dones.common_dones.MultiagentSuccessDoneFunction",
        "config": { success_function_name: "RejoinSuccessDoneFunction" },
      }
    ]
  }
}