# ---------------------------------------------------------------------------
# //
#
# Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
# Reinforcement Learning (RL) Core contributed by the:
#  -  () Team
#  - Safe Autonomy (SA) Team
#
# This is a US Government Work not subject to copyright protection in the US.
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ---------------------------------------------------------------------------

{
  "simulator": {
    "type": "Dubins2dSimulator",
    "config": {
      "step_size": 1
    },
  },
  "simulator_reset_parameters": {
  },
  "platforms": "DubinsSimulator_Platforms",
  "plugin_paths": ["saferl.platforms", "saferl.simulators"],
  "episode_parameter_provider": {
    "type": "act3_rl_core.episode_parameter_providers.simple.SimpleParameterProvider"
  },
  "dones": {
    "shared": [
      {
        "functor": "saferl.dones.rejoin_dones.RejoinDone",
        "config": {agent_name: "blue0"},
      }
    ]
  },
  "sanity_check_obs": 1,  # Raise for faster runs
}