#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Reinforcement Learning (RL) Core Extension.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------

####################################################################
# Override values used by the setup
####################################################################
experiment_class: scripts.test_cwh_rta_final.DockingRTAExperiment
config:
  rllib_config_updates: &rllib_config_updates
    rollout_fragment_length: 2000
    train_batch_size: 12000
    num_workers: 6

  # No overrides for ray as there are no changes
  ray_config_updates: &ray_config_updates
    local_mode: False

  # Change the default path for saving out the data
  env_config_updates: &env_config_updates
    TrialName: CWH-3D-DOCKING-RTA-TEST
    output_path: ./output/env/

  # Change the default path for saving out the data
  tune_config_updates: &tune_config_updates

  ####################################################################
  # Setup the actual keys used by the code
  # Note that items are patched from the update section
  ###################################################################
  rllib_configs:
    default: [!include ../../../common/ray/rllib.yml, *rllib_config_updates]
    local: [!include ../../../common/ray/rllib.yml,  *rllib_config_updates]

  ray_config: [!include ../../../common/ray/ray.yml, *ray_config_updates]
  env_config: [!include ../environments/environment.yml, *env_config_updates]
  tune_config: [!include ../../../common/ray/tune.yml, *tune_config_updates]

