"""
--------------------------------------------------------------------------
Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
Reinforcement Learning (RL) Core  Extension.

This is a US Government Work not subject to copyright protection in the US.

The use, dissemination or disclosure of data in this file is subject to
limitation or restriction. See accompanying README and LICENSE for details.
---------------------------------------------------------------------------
"""

"agent": "corl.agents.base_agent.TrainableBaseAgent"
"config": {
    "parts": [
        {"part": "Controller_RollRate", "config": {"axis": 0}},
        {"part": "Controller_PitchRate", "config": {"axis": 1}},
        {"part": "Controller_Acceleration", "config": {"axis": 2}},
        {"part": "Sensor_Position"},
        {"part": "Sensor_Velocity"},
        {"part": "Sensor_Heading"},
        {"part": "Sensor_Flight_Path_Angle"},
        {"part": "Sensor_Time"},
    ],
    "episode_parameter_provider": {
      "type": "corl.episode_parameter_providers.simple.SimpleParameterProvider"
    },
    "simulator_reset_parameters": {
      "x": 5000,
      "y": 0,
      "z": 10000,
      "heading": 0,
      "v": 200,
      "gamma": 0,
      "roll": 0
    },
    "glues": [
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config": {
                "controller": "Controller_Acceleration",
                "training_export_behavior": "EXCLUDE",
            },
        },
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config":{
                "controller": "Controller_PitchRate",
                "training_export_behavior": "EXCLUDE",
            }
        },
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config":{
                "controller": "Controller_RollRate",
                "training_export_behavior": "EXCLUDE",
            }
        },
        {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config": {"sensor": "Sensor_Position"},
        },
        {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config": {"sensor": "Sensor_Velocity"},
        },
        {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config": {"sensor": "Sensor_Heading"},
        },
        {
          "functor": "corl.glues.common.observe_sensor.ObserveSensor",
          "config": { "sensor": "Sensor_Flight_Path_Angle" },
        },
        {
          "functor": "corl.glues.common.observe_sensor.ObserveSensor",
          "config": {
            "sensor": "Sensor_Time",
            "normalization": {
              "enabled": False,
            }
          },
        },
    ],
    "dones": [],
    "rewards": [
        {
            "name": "RejoinNoReward",
            "functor": "saferl.core.rewards.rejoin_rewards.RejoinReward",
            "config": {
                "reward": 0,
                "radius": 150,
                "offset": [ 500, 500, 0 ],
                "lead": "red0",
            }
        },
    ],
}