#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Reinforcement Learning (RL) Core  Extension.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------

"agent": "corl.agents.base_agent.TrainableBaseAgent"
"config": {
    "parts": [
        {"part": "Controller_YawRate", "config": {"axis": 0}},
        {"part": "Controller_Acceleration", "config": { "axis": 1 }},
        {"part": "Sensor_Relative_Position", "config": {"oriented": True}},
        {"part": "Sensor_Relative_Rejoin_Position", "config": {"oriented": True, "offset": [500, 500]}},
        {"part": "Sensor_Velocity", "config": {"oriented": True}},
        {"part": "Sensor_Partner_Velocity", "config": {"oriented": True}},
    ],
    "episode_parameter_provider": {
      "type": "corl.episode_parameter_providers.simple.SimpleParameterProvider"
    },
    "simulator_reset_parameters": {
      "x": 0,
      "y": 0,
      "z": 0,
      "heading": 0,
      "v": 200
    },
    "glues": [
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config": {
                "controller": "Controller_Acceleration",
                "training_export_behavior": "EXCLUDE",
                "normalization": {
                    "enabled": False,
                }
            },
        },
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config":{
                "controller": "Controller_YawRate",
                "training_export_behavior": "EXCLUDE",
                "normalization": {
                  "enabled": False,
                }
            }
        },
        {
          "functor": "corl.glues.common.magnitude.MagnitudeGlue",
          "config": {
            "normalization": {
                "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
                "config": {
                  "mu": 0,
                  "sigma": 1000,
              },
            },
          },
          "wrapped": {
              "functor": "corl.glues.common.observe_sensor.ObserveSensor",
              "config":{
                  "sensor": "Sensor_Relative_Position",
              },
          },
        },
        {
          "functor": "corl.glues.common.unit_vector_glue.UnitVectorGlue",
          "config": {
            "normalization": {
              "config": {
                "mu": 0,
                "sigma": [1, 1],
              }
            }
          },
          "wrapped": {
              "functor": "corl.glues.common.observe_sensor.ObserveSensor",
              "config":{
                  "sensor": "Sensor_Relative_Position",
              },
          },
        },
        {
          "functor": "corl.glues.common.magnitude.MagnitudeGlue",
          "config": {
            "normalization": {
                "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
                "config": {
                  "mu": 0,
                  "sigma": 1000,
              },
            },
          },
          "wrapped": {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config":{
              "sensor": "Sensor_Relative_Rejoin_Position",
            },
          },
        },
        {
          "functor": "corl.glues.common.unit_vector_glue.UnitVectorGlue",
          "config": {
            "normalization": {
              "config": {
                 "mu": 0,
                 "sigma": [1, 1],
               }
             },
           },
           "wrapped": {
               "functor": "corl.glues.common.observe_sensor.ObserveSensor",
               "config":{
                 "sensor": "Sensor_Relative_Rejoin_Position",
               },
           },
        },
        {
          "functor": "corl.glues.common.magnitude.MagnitudeGlue",
          "config": {
            "normalization": {
                "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
                "config": {
                  "mu": 0,
                  "sigma": 400,
              },
            },
          },
          "wrapped": {
              "functor": "corl.glues.common.observe_sensor.ObserveSensor",
              "config":{
                  "sensor": Sensor_Velocity,
              },
          },
        },
        {
          "functor": "corl.glues.common.unit_vector_glue.UnitVectorGlue",
          "config": {
            "normalization": {
              "config": {
                "mu": 0,
                "sigma": [1, 1],
              }
            }
          },
          "wrapped": {
              "functor": "corl.glues.common.observe_sensor.ObserveSensor",
              "config":{
                  "sensor": Sensor_Velocity,
              },
          },
        },
        {
          "functor": "corl.glues.common.magnitude.MagnitudeGlue",
          "config": {
            "normalization": {
              "normalizer": "corl.libraries.normalization.StandardNormalNormalizer",
              "config": {
                "mu": 0,
                "sigma": 400,
              },
            },
          },
          "wrapped": {
              "functor": "corl.glues.common.observe_sensor.ObserveSensor",
              "config":{
                  "sensor": Sensor_Partner_Velocity,
              },
          },
        },
        {
          "functor": "corl.glues.common.unit_vector_glue.UnitVectorGlue",
          "config": {
            "normalization": {
              "config": {
                "mu": 0,
                "sigma": [1, 1],
              }
            }
          },
          "wrapped": {
              "functor": "corl.glues.common.observe_sensor.ObserveSensor",
              "config":{
                  "sensor": Sensor_Partner_Velocity,
              },
          },
        },
    ],
    "dones": [
        {
            "functor": "saferl.dones.common_dones.TimeoutDoneFunction",
            "config":{
                "max_sim_time": 1000,
            },
        },
        {
            "functor": "saferl.dones.rejoin_dones.MaxDistanceDoneFunction",
            "config":{
                "max_distance": 40000,
                "lead": "red0",
            },
        },
        {
            "functor": "saferl.dones.rejoin_dones.CrashDoneFunction",
            "config":{
                "safety_margin": 10,
                "lead": "red0",
            },
        },
        {
            "functor": "saferl.dones.rejoin_dones.RejoinSuccessDone",
            "config":{
                "radius": 150,
                "offset": [500, 500],
                "lead": "red0",
                "step_size": 1,
                "success_time": 20,
            },
        },
    ],
    "rewards": [
        {
            "name": "RejoinDistanceExponentialChangeReward",
            "functor": "saferl.rewards.rejoin_rewards.RejoinDistanceExponentialChangeReward",
            "config": {
                "offset": [ 500, 500 ],
                "lead": "red0",
                "pivot": 5000.0,
            }
        },
        {
            "name": "RejoinReward",
            "functor": "saferl.rewards.rejoin_rewards.RejoinReward",
            "config": {
                "reward": 0.1,
                "refund": True,
                "radius": 150,
                "offset": [ 500, 500 ],
                "lead": "red0",
            }
        },
        {
            "name": "RejoinFirstTimeReward",
            "functor": "saferl.rewards.rejoin_rewards.RejoinFirstTimeReward",
            "config": {
                "reward": 0.25,
                "radius": 150,
                "offset": [ 500, 500 ],
                "lead": "red0",
            }
        },
        {
            "name": "RejoinSuccessReward",
            "functor": "saferl.rewards.rejoin_rewards.RejoinSuccessReward",
            "config": {
                "reward": 1,
                "radius": 150,
                "offset": [ 500, 500 ],
                "lead": "red0",
                "step_size": 1,
                "success_time": 20,
            }
        },
        {
            "name": "RejoinFailureReward",
            "functor": "saferl.rewards.rejoin_rewards.RejoinFailureReward",
            "config": {
                "crash_reward": -1,
                "distance_reward": -1,
                "timeout_reward": -1,
                "leave_rejoin_reward": 0,
                "radius": 150,
                "offset": [ 500, 500 ],
                "lead": "red0",
                "max_time": 1000,
                "max_distance": 40000,
                "safety_margin": 100,
            }
        },
    ],
}