"""
--------------------------------------------------------------------------
Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
Reinforcement Learning (RL) Core  Extension.

This is a US Government Work not subject to copyright protection in the US.

The use, dissemination or disclosure of data in this file is subject to
limitation or restriction. See accompanying README and LICENSE for details.
---------------------------------------------------------------------------
"""

"agent": "corl.agents.base_agent.TrainableBaseAgent"
"config": {
    "parts": [
        {"part": "Controller_YawRate", "config": {"axis": 0}},
        { "part": "Controller_Acceleration", "config": { "axis": 1 } },
        {"part": "Sensor_Position"},
        {"part": "Sensor_Velocity"},
        {"part": "Sensor_Heading"},
        { "part": "Sensor_Time" },
    ],
    "episode_parameter_provider": {
      "type": "corl.episode_parameter_providers.simple.SimpleParameterProvider"
    },
    "simulator_reset_parameters": {
      "x": 1000,
      "y": 0,
      "z": 0,
      "heading": 0,
      "v": 200
    },
    "glues": [
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config": {
                "controller": "Controller_Acceleration",
            },
        },
        {
            "functor": "corl.glues.common.controller_glue.ControllerGlue",
            "config":{
                "controller": "Controller_YawRate",
            }
        },
        {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config": {"sensor": "Sensor_Position"},
        },
        {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config": {"sensor": "Sensor_Velocity"},
        },
        {
            "functor": "corl.glues.common.observe_sensor.ObserveSensor",
            "config": {"sensor": "Sensor_Heading"},
        },
        {
          "functor": "corl.glues.common.observe_sensor.ObserveSensor",
          "config": {
            "sensor": "Sensor_Time",
            "normalization": {
              "enabled": False,
            }
          },
        },
    ],
    "dones": [],
    "rewards": [
        {
            "name": "RejoinNoReward",
            "functor": "saferl.core.rewards.rejoin_rewards.RejoinReward",
            "config": {
                "reward": 0,
                "radius": 150,
                "offset": [ 500, 500 ],
                "lead": "red0",
            }
        },
    ],
}