[
{  # local position
  functor: "safe_autonomy_sims.glues.six_dof_glues.RotateVectorToLocalRef3d",
  config: {
    mode: "quaternion",
    normalization: {
      enabled: True,
      normalizer: "corl.libraries.normalization.StandardNormalNormalizer",
      config: {
        mu: 0.0,
        sigma: [100, 100, 100],
      }
    },
  },
  wrapped: [
  !include-extend ./rotation_quaternion.yml,

  {
    "functor": "corl.glues.common.observe_sensor.ObserveSensor",
    "config": {
      "sensor": "Sensor_RelativeChiefPosition",
      "output_units": "m",
      "normalization": {
        "enabled": False,
      },
    },
  }
  ]
},
{  # local position MagNorm representation
  functor: "safe_autonomy_sims.glues.six_dof_glues.MagNorm3DGlue",
  config: {
    normalization: {
      enabled: True,
      normalizer: "corl.libraries.normalization.StandardNormalNormalizer",
      config: {
        mu: 0.0,
        sigma: [175, 1.0, 1.0, 1.0],
      }
    }
  },
  wrapped: {
    "functor": "safe_autonomy_sims.glues.six_dof_glues.RotateVectorToLocalRef3d",
    "config": {
      "normalization": {
        "enabled": False,
      },
    },
    "wrapped": [
      !include-extend ./rotation_quaternion.yml,

      {
        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
        "config": {
          "sensor": "Sensor_RelativeChiefPosition",
          "output_units": "m",
          "normalization": {
            "enabled": False,
          }
        }
      }
    ]
  }
},
{  # local velocity
  functor: "safe_autonomy_sims.glues.six_dof_glues.RotateVectorToLocalRef3d",
  config: {
    normalization: {
      enabled: True,
      normalizer: "corl.libraries.normalization.StandardNormalNormalizer",
      config: {
        mu: 0.0,
        sigma: [0.5, 0.5, 0.5],
      }
    },
  },
  wrapped: [
  !include-extend ./rotation_quaternion.yml,

  {
    "functor": "corl.glues.common.observe_sensor.ObserveSensor",
    "config": {
      "sensor": "Sensor_RelativeChiefVelocity",
      "output_units": "m/s",
      "normalization": {
        "enabled": False,
      },
    },
  }
  ]
},
{  # local velocity MagNorm representation
  functor: "safe_autonomy_sims.glues.six_dof_glues.MagNorm3DGlue",
  config: {
    normalization: {
      enabled: True,
      normalizer: "corl.libraries.normalization.StandardNormalNormalizer",
      config: {
        mu: 0.0,
        sigma: [0.866, 1.0, 1.0, 1.0],
      }
    }
  },
  wrapped: {
    "functor": "safe_autonomy_sims.glues.six_dof_glues.RotateVectorToLocalRef3d",
    "config": {
      "normalization": {
        "enabled": False,
      },
    },
    "wrapped": [
      !include-extend ./rotation_quaternion.yml,

      {
        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
        "config": {
          "sensor": "Sensor_RelativeChiefVelocity",
          "output_units": "m/s",
          "normalization": {
            "enabled": False,
          }
        }
      }
    ]
  }
},
# {
#   functor: "corl.glues.common.observe_sensor.ObserveSensor",
#   config: {
#     sensor: "Sensor_OrbitStability",
#     normalization: {
#       normalizer: "corl.libraries.normalization.StandardNormalNormalizer",
#       config: {
#         mu: 0.0,
#         sigma: [10.0]
#       },
#     },
#   },
# },
]
