[
{  # local position
  functor: "safe_autonomy_sims.glues.osam3d_glues.RotateVectorToLocalRef3d",
  config: {
    normalization: {
      enabled: True,
      normalizer: "corl.libraries.normalization.StandardNormalNormalizer",
      config: {
        mu: 0.0,
        sigma: [100, 100, 100],
      }
    },
  },
  wrapped: [
  {
    "functor": "corl.glues.common.observe_sensor.ObserveSensor",
    "config": {
      "sensor": "Sensor_Quaternion",
      "normalization": {
        "enabled": False,
      },
    },
  },
  {
    "functor": "corl.glues.common.observe_sensor.ObserveSensor",
    "config": {
      "sensor": "Sensor_RelativeChiefPosition",
      "output_units": ["m", "m", "m"],
      "normalization": {
        "enabled": False,
      },
    },
  }
  ]
},
{  # local position MagNorm representation
  functor: "safe_autonomy_sims.glues.osam3d_glues.MagNorm3DGlue",
  config: {
    normalization: {
      enabled: True,
      normalizer: "corl.libraries.normalization.StandardNormalNormalizer",
      config: {
        mu: 0.0,
        sigma: [175, 1.0, 1.0, 1.0],
      }
    }
  },
  wrapped: {
    "functor": "safe_autonomy_sims.glues.osam3d_glues.RotateVectorToLocalRef3d",
    "config": {
      "normalization": {
        "enabled": False,
      },
    },
    "wrapped": [
      {
        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
        "config": {
          "sensor": "Sensor_Quaternion",
          "normalization": {
            "enabled": False,
          }
        }
      },
      {
        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
        "config": {
          "sensor": "Sensor_RelativeChiefPosition",
          "output_units": ["m", "m", "m"],
          "normalization": {
            "enabled": False,
          }
        }
      }
    ]
  }
},
{  # local velocity
  functor: "safe_autonomy_sims.glues.osam3d_glues.RotateVectorToLocalRef3d",
  config: {
    normalization: {
      enabled: True,
      normalizer: "corl.libraries.normalization.StandardNormalNormalizer",
      config: {
        mu: 0.0,
        sigma: [0.5, 0.5, 0.5],
      }
    },
  },
  wrapped: [
  {
    "functor": "corl.glues.common.observe_sensor.ObserveSensor",
    "config": {
      "sensor": "Sensor_Quaternion",
      "normalization": {
        "enabled": False,
      },
    },
  },
  {
    "functor": "corl.glues.common.observe_sensor.ObserveSensor",
    "config": {
      "sensor": "Sensor_RelativeChiefVelocity",
      "output_units": ["m/s", "m/s", "m/s"],
      "normalization": {
        "enabled": False,
      },
    },
  }
  ]
},
{  # local velocity MagNorm representation
  functor: "safe_autonomy_sims.glues.osam3d_glues.MagNorm3DGlue",
  config: {
    normalization: {
      enabled: True,
      normalizer: "corl.libraries.normalization.StandardNormalNormalizer",
      config: {
        mu: 0.0,
        sigma: [0.866, 1.0, 1.0, 1.0],
      }
    }
  },
  wrapped: {
    "functor": "safe_autonomy_sims.glues.osam3d_glues.RotateVectorToLocalRef3d",
    "config": {
      "normalization": {
        "enabled": False,
      },
    },
    "wrapped": [
      {
        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
        "config": {
          "sensor": "Sensor_Quaternion",
          "normalization": {
            "enabled": False,
          }
        }
      },
      {
        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
        "config": {
          "sensor": "Sensor_RelativeChiefVelocity",
          "output_units": ["m/s", "m/s", "m/s"],
          "normalization": {
            "enabled": False,
          }
        }
      }
    ]
  }
},
# {
#   functor: "corl.glues.common.observe_sensor.ObserveSensor",
#   config: {
#     sensor: "Sensor_OrbitStability",
#     normalization: {
#       normalizer: "corl.libraries.normalization.StandardNormalNormalizer",
#       config: {
#         mu: 0.0,
#         sigma: [10.0]
#       },
#     },
#   },
# },
]
