#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Reinforcement Learning Core (CoRL) Safe Autonomy Extension.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------

"agent": "corl.agents.base_agent.TrainableBaseAgent"
"config": {
    "frame_rate": 0.1,  # Hz
    "parts": [
        {"part": "RateController", "config": {"name": "X Thrust", "property_class": "safe_autonomy_sims.platforms.cwh.cwh_properties.ThrustProp", "axis": 0, properties: {name: "x_thrust"}}},
        {"part": "RateController", "config": {"name": "Y Thrust", "property_class": "safe_autonomy_sims.platforms.cwh.cwh_properties.ThrustProp", "axis": 1, properties: {name: "y_thrust"}}},
        {"part": "RateController", "config": {"name": "Z Thrust", "property_class": "safe_autonomy_sims.platforms.cwh.cwh_properties.ThrustProp", "axis": 2, properties: {name: "z_thrust"}}},
        {"part": "RateController", "config": {"name": "X Moment", "property_class": "safe_autonomy_sims.platforms.cwh.cwh_properties.MomentProp", "axis": 3, properties: {name: "x_moment"}}},
        {"part": "RateController", "config": {"name": "Y Moment", "property_class": "safe_autonomy_sims.platforms.cwh.cwh_properties.MomentProp", "axis": 4, properties: {name: "y_moment"}}},
        {"part": "RateController", "config": {"name": "Z Moment", "property_class": "safe_autonomy_sims.platforms.cwh.cwh_properties.MomentProp", "axis": 5, properties: {name: "z_moment"}}},
        {"part": "Sensor_Position"},
        {"part": "Sensor_Velocity"},
        {"part": "Sensor_InspectedPoints", "config": {"inspector_entity_name": "blue0"}},
        {"part": "Sensor_UninspectedPoints", "config": {"inspector_entity_name": "blue0", "inspection_entity_name": "chief"}},
        {"part": "Sensor_SunAngle"},
        {"part": "Sensor_EntityPosition", "config": {"name": "reference_position", "entity_name": "chief"}}, # Ensure reference position sensor name consistent with dones and rewards
        {"part": "Sensor_EntityVelocity", "config": {"name": "reference_velocity", "entity_name": "chief"}}, # Ensure reference position sensor name consistent with dones and rewards
        {"part": "Sensor_Quaternion"},
        {"part": "Sensor_AngularVelocity"},
    ],
    "episode_parameter_provider": {
      "type": "corl.episode_parameter_providers.simple.SimpleParameterProvider"
    },
    "simulator_reset_parameters": !include-extend ../common/initializer/six_dof.yml,
    "glues": [
        !include-extend ../common/controller/translational.yml,
        !include-extend ../common/controller/rotation.yml,
        !include-extend ../common/sensors/common.yml,
        !include-extend ../common/sensors/rotation.yml,
        !include-extend ../common/sensors/illumination.yml,
    ],
    "dones": [
        !include-extend ../common/dones.yml,
    ],
    "rewards": [
        !include-extend ../common/rewards/common.yml,
    ],
    "reference_store": !include ../../parameters/parameters.yml
}
