{
  "timeout": 2000,
  "max_distance": 10000,
  "docking_region_radius": 0.5,
  "velocity_threshold": 0.2,
  "threshold_distance": 0.5,
  "mean_motion": 0.001027,
  "lower_bound": False,
  "reference_position_sensor_name": "reference_position",
  "reference_velocity_sensor_name": "reference_velocity",
}